# Generated by Django 5.1.4 on 2025-01-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave'), ('sick', 'Sick Leave')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
