# Generated by Django 5.1.4 on 2025-01-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
