# Generated by Django 5.1.4 on 2025-01-20 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave_manager', '0003_yearlyleavebalance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yearlyleavebalance',
            old_name='used_leave',
            new_name='leaves_taken',
        ),
    ]
